version: "3"
services:
 postgres:
     image: postgres:12.1
     container_name: postgres
     volumes:
       - ./postgres:/var/lib/postgresql/data
       - ./rails:/myapp
     environment:
       POSTGRES_DB: "${DATABASE_NAME}"
       POSTGRES_USER: "${DATABASE_USERNAME}"
       POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"

 ruby:
    build: ./rails/
    container_name: ruby
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      database: "${DATABASE_NAME}"
      username: "${DATABASE_USERNAME}"
      password: "${DATABASE_PASSWORD}"
      port: "${DATABASE_PORT}"
      host: "${DATABASE_HOST}"
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./rails:/myapp
 ang:
    container_name: ang
    build: ./angular
    # environment:
    #   API_IP: "${API_IP}"
    ports:
      - "8080:80"
